default:
  title: 'Untitled-1'
  # choose from breeze, candy, crimson, falcon, meadow, midnight, raindrop, sunset
  theme: breeze
  # choose from 16, 32, 64, 128
  padding: 32
  background: true
  darkMode: true
  language: auto
  spoiler: false
  generateUrl: false

channels:
  - id: '1051137122691731589'
    theme: midnight
    padding: 64
    spoiler: true
    generateUrl: true
